apiVersion: v1
kind: Secret
metadata:
  name: manager-group-secret
  namespace: manager-group
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: aEh3cm1QNVdsSHpyQTNXYjM=  # 123456 em base64
  APP_KEY: c2VjcmV0LWtleS1oZXJl  # secret-key-here em base64
  SENTRY_DSN: aHR0cHM6Ly83YzAyYTAyMzZiMDI4NjhjZjgyNjdiZjdlY2EyZGRmM0BvNDUxMDAwMjU5ODMxMzk4NC5pbmdlc3QudXMuc2VudHJ5LmlvLzQ1MTAwMDI2MDQ0NzQzNjg=  # Sentry DSN em base64
  WHATSAPP_API_KEY: N0M3NTBDQjUzMzQ4LTREMkUtOUFERC1CQzdEQkQ1MkMxRTU=  # 7C750CB53348-4D2E-9AFD-BC7DBD52C1E5 em base64